# Sorting split images out

In [48]:
import glob
import os
import re

import pandas as pd

In [3]:
glob.glob('/mnt/OPERA3/Nathan/data/macrohet/mtb_tissue_localisation/results/split_image_fix/*pkl')

['/mnt/OPERA3/Nathan/data/macrohet/mtb_tissue_localisation/results/split_image_fix/rep1_mouse_6_label_top_updated.pkl',
 '/mnt/OPERA3/Nathan/data/macrohet/mtb_tissue_localisation/results/split_image_fix/rep1_updated.pkl',
 '/mnt/OPERA3/Nathan/data/macrohet/mtb_tissue_localisation/results/split_image_fix/rep2_updated.pkl',
 '/mnt/OPERA3/Nathan/data/macrohet/mtb_tissue_localisation/results/split_image_fix/rep2_mouse3_top.zarr_updated.pkl',
 '/mnt/OPERA3/Nathan/data/macrohet/mtb_tissue_localisation/results/split_image_fix/rep2_mouse3_bot.zarr_updated.pkl',
 '/mnt/OPERA3/Nathan/data/macrohet/mtb_tissue_localisation/results/split_image_fix/rep2_mouse4_bot.zarr_updated.pkl',
 '/mnt/OPERA3/Nathan/data/macrohet/mtb_tissue_localisation/results/split_image_fix/rep2_mouse4_top.zarr_updated.pkl',
 '/mnt/OPERA3/Nathan/data/macrohet/mtb_tissue_localisation/results/split_image_fix/rep2_mouse5_bot.zarr_updated.pkl',
 '/mnt/OPERA3/Nathan/data/macrohet/mtb_tissue_localisation/results/split_image_fix/rep2_mouse5_top.zarr_updated.pkl',
 '/mnt/OPERA3/Nathan/data/macrohet/mtb_tissue_localisation/results/split_image_fix/rep2_mouse6_bot.zarr_updated.pkl',
 '/mnt/OPERA3/Nathan/data/macrohet/mtb_tissue_localisation/results/split_image_fix/rep2_mouse6_top.zarr_updated.pkl',
 '/mnt/OPERA3/Nathan/data/macrohet/mtb_tissue_localisation/results/split_image_fix/rep2_mouse9_bot.zarr_updated.pkl',
 '/mnt/OPERA3/Nathan/data/macrohet/mtb_tissue_localisation/results/split_image_fix/rep2_mouse9_top.zarr_updated.pkl',
 '/mnt/OPERA3/Nathan/data/macrohet/mtb_tissue_localisation/results/split_image_fix/rep2_mouse10_bot.zarr_updated.pkl',
 '/mnt/OPERA3/Nathan/data/macrohet/mtb_tissue_localisation/results/split_image_fix/rep2_mouse10_top.zarr_updated.pkl',
 '/mnt/OPERA3/Nathan/data/macrohet/mtb_tissue_localisation/results/split_image_fix/rep2_mouse11_bot.zarr_updated.pkl',
 '/mnt/OPERA3/Nathan/data/macrohet/mtb_tissue_localisation/results/split_image_fix/rep2_mouse11_top.zarr_updated.pkl',
 '/mnt/OPERA3/Nathan/data/macrohet/mtb_tissue_localisation/results/split_image_fix/rep2_mouse12_bot.zarr_updated.pkl',
 '/mnt/OPERA3/Nathan/data/macrohet/mtb_tissue_localisation/results/split_image_fix/rep2_mouse12_top.zarr_updated.pkl',
 '/mnt/OPERA3/Nathan/data/macrohet/mtb_tissue_localisation/results/split_image_fix/rep2_mouse13_bot.zarr_updated.pkl',
 '/mnt/OPERA3/Nathan/data/macrohet/mtb_tissue_localisation/results/split_image_fix/rep2_mouse13_top.zarr_updated.pkl',
 '/mnt/OPERA3/Nathan/data/macrohet/mtb_tissue_localisation/results/split_image_fix/rep2_mouse14_bot.zarr_updated.pkl',
 '/mnt/OPERA3/Nathan/data/macrohet/mtb_tissue_localisation/results/split_image_fix/rep2_mouse14_top.zarr_updated.pkl',
 '/mnt/OPERA3/Nathan/data/macrohet/mtb_tissue_localisation/results/split_image_fix/rep2_mouse15_bot.zarr_updated.pkl',
 '/mnt/OPERA3/Nathan/data/macrohet/mtb_tissue_localisation/results/split_image_fix/rep2_mouse15_top.zarr_updated.pkl',
 '/mnt/OPERA3/Nathan/data/macrohet/mtb_tissue_localisation/results/split_image_fix/rep2_mouse16_bot.zarr_updated.pkl',
 '/mnt/OPERA3/Nathan/data/macrohet/mtb_tissue_localisation/results/split_image_fix/rep2_mouse16_top.zarr_updated.pkl',
 '/mnt/OPERA3/Nathan/data/macrohet/mtb_tissue_localisation/results/split_image_fix/rep1_mouse6_bot.zarr_updated.pkl',
 '/mnt/OPERA3/Nathan/data/macrohet/mtb_tissue_localisation/results/split_image_fix/rep1_mouse6_top.zarr_updated.pkl',
 '/mnt/OPERA3/Nathan/data/macrohet/mtb_tissue_localisation/results/split_image_fix/rep1_mouse7_bot.zarr_updated.pkl',
 '/mnt/OPERA3/Nathan/data/macrohet/mtb_tissue_localisation/results/split_image_fix/rep1_mouse7_top.zarr_updated.pkl',
 '/mnt/OPERA3/Nathan/data/macrohet/mtb_tissue_localisation/results/split_image_fix/rep1_mouse8_left.zarr_updated.pkl',
 '/mnt/OPERA3/Nathan/data/macrohet/mtb_tissue_localisation/results/split_image_fix/rep1_mouse8_right.zarr_updated.pkl',
 '/mnt/OPERA3/Nathan/data/macrohet/mtb_tissue_localisation/results/split_image_fix/rep1_mouse9_bot.zarr_updated.pkl',
 '/mnt/OPERA3/Nathan/data/macrohet/mtb_tissue_localisation/results/split_image_fix/rep1_mouse9_top.zarr_updated.pkl',
 '/mnt/OPERA3/Nathan/data/macrohet/mtb_tissue_localisation/results/split_image_fix/rep1_mouse10_left.zarr_updated.pkl',
 '/mnt/OPERA3/Nathan/data/macrohet/mtb_tissue_localisation/results/split_image_fix/rep1_mouse10_right.zarr_updated.pkl',
 '/mnt/OPERA3/Nathan/data/macrohet/mtb_tissue_localisation/results/split_image_fix/rep1_mouse11_left.zarr_updated.pkl',
 '/mnt/OPERA3/Nathan/data/macrohet/mtb_tissue_localisation/results/split_image_fix/rep1_mouse11_right.zarr_updated.pkl']

In [4]:
rep1_df = pd.read_pickle('/mnt/OPERA3/Nathan/data/macrohet/mtb_tissue_localisation/results/split_image_fix/rep1_updated.pkl')
rep2_df = pd.read_pickle('/mnt/OPERA3/Nathan/data/macrohet/mtb_tissue_localisation/results/split_image_fix/rep2_updated.pkl')

In [26]:
split_df = pd.concat([rep1_df, rep2_df])

In [27]:
# 1. Extract 'rep' (finds 'rep' followed by any number of digits)
split_df['rep_N'] = split_df['zarr_address'].str.extract(r'rep(\d+)').astype(int)

# 2. Extract 'mouse_n' (finds 'mouse' followed by any number of digits)
split_df['mouse_N'] = split_df['zarr_address'].str.extract(r'mouse(\d+)').astype(int)

# 3. Extract 'split' (Removes '.zarr' and takes the last 3 characters remaining)
# This captures 'bot' from '..._bot.zarr'
split_df['split'] = split_df['zarr_address'].str.replace('.zarr', '', regex=False).str[-3:]

# Check the result
print(split_df[['zarr_address', 'rep_N', 'mouse_N', 'split']].head())

           zarr_address  rep_N  mouse_N split
0  rep1_mouse6_bot.zarr      1        6   bot
1  rep1_mouse6_bot.zarr      1        6   bot
2  rep1_mouse6_bot.zarr      1        6   bot
3  rep1_mouse6_bot.zarr      1        6   bot
4  rep1_mouse6_bot.zarr      1        6   bot

In [28]:
split_df

,zarr_address,region_id,mean_intensity_ch1,mean_intensity_ch2,area,bbox_rmin,bbox_rmax,bbox_cmin,bbox_cmax,rep_N,mouse_N,split
0,rep1_mouse6_bot.zarr,1,805.800000,1955.400000,35.0,125,143,14610,14626,1,6,bot
1,rep1_mouse6_bot.zarr,2,1001.546667,2004.760000,75.0,819,837,19047,19073,1,6,bot
2,rep1_mouse6_bot.zarr,3,387.137931,597.502463,203.0,913,943,13430,13460,1,6,bot
3,rep1_mouse6_bot.zarr,4,678.364865,844.472973,74.0,1350,1372,26076,26095,1,6,bot
4,rep1_mouse6_bot.zarr,5,458.293839,701.293839,633.0,1458,1499,8385,8424,1,6,bot
...,...,...,...,...,...,...,...,...,...,...,...,...
372342,rep2_mouse16_top.zarr,501,3168.583333,805.000000,156.0,34194,34228,2815,2845,2,16,top
372343,rep2_mouse16_top.zarr,502,3707.631579,913.567251,171.0,34204,34231,2751,2785,2,16,top
372344,rep2_mouse16_top.zarr,503,4872.142857,1180.142857,7.0,34211,34224,18594,18607,2,16,top
372345,rep2_mouse16_top.zarr,504,3681.236842,837.684211,38.0,34244,34263,765,781,2,16,top
372346,rep2_mouse16_top.zarr,505,5834.728395,1165.814815,81.0,34299,34317,17023,17049,2,16,top

In [29]:
split_df[['rep_N', 'mouse_N']].drop_duplicates()

        rep_N  mouse_N
0           1        6
591         1        7
1513        1        8
1697        1        9
2146        1       10
10173       1       11
0           2        3
4090        2        4
7729        2        5
10449       2        6
12280       2        9
13626       2       10
18557       2       11
22104       2       12
364150      2       13
364880      2       14
368071      2       15
370952      2       16

In [12]:
other_rep1_df = pd.read_pickle('/mnt/OPERA3/Nathan/data/macrohet/mtb_tissue_localisation/results/rep1_sc_results_w_bb.pkl')
other_rep2_df = pd.read_pickle('/mnt/OPERA3/Nathan/data/macrohet/mtb_tissue_localisation/results/rep2_sc_results_w_bb.pkl')

In [30]:
nonsplit_df = pd.concat([other_rep1_df, other_rep2_df])
nonsplit_df

,zarr_address,region_id,mean_intensity_ch1,mean_intensity_ch2,area,bbox_rmin,bbox_rmax,bbox_cmin,bbox_cmax,mouse_N,rep_N,condition
16762,20250901_40X_TimerMtb_BP_mice2_mice3_mice4_DAP...,1,669.458333,1154.916667,72.0,12,28,24285,24311,2,1.0,DMSO
16763,20250901_40X_TimerMtb_BP_mice2_mice3_mice4_DAP...,2,394.212121,602.606061,33.0,31,46,25260,25278,2,1.0,DMSO
16764,20250901_40X_TimerMtb_BP_mice2_mice3_mice4_DAP...,3,613.163636,943.381818,55.0,43,59,25134,25166,2,1.0,DMSO
16765,20250901_40X_TimerMtb_BP_mice2_mice3_mice4_DAP...,4,737.836957,1462.576087,92.0,46,69,24763,24787,2,1.0,DMSO
16766,20250901_40X_TimerMtb_BP_mice2_mice3_mice4_DAP...,5,257.228070,396.228070,57.0,47,64,27340,27364,2,1.0,DMSO
...,...,...,...,...,...,...,...,...,...,...,...,...
49474,20251109_40X_Mouse16_Timer_PZA-RIF_20251109_09...,886,0.000000,0.000000,93.0,22391,22421,7838,7859,NaN,NaN,NaN
49475,20251109_40X_Mouse16_Timer_PZA-RIF_20251109_09...,887,0.000000,0.000000,43.0,23186,23203,4855,4877,NaN,NaN,NaN
49476,20251109_40X_Mouse16_Timer_PZA-RIF_20251109_09...,888,156.782051,119.256410,78.0,23481,23507,18800,18817,NaN,NaN,NaN
49477,20251109_40X_Mouse16_Timer_PZA-RIF_20251109_09...,889,1966.617391,445.739130,115.0,24371,24402,11851,11878,NaN,NaN,NaN
49478,20251109_40X_Mouse16_Timer_PZA-RIF_20251109_09...,890,588.700000,197.000000,40.0,24783,24802,16000,16020,NaN,NaN,NaN

### Drop split images from OG nonsplit DF

In [31]:
# 1. Create a set of the unique (rep, mouse_n) tuples to remove
keys_to_remove = set(zip(split_df['rep_N'], split_df['mouse_N']))
print(keys_to_remove)
# 2. Define a function to check if a row is in that set
# (Assumes nonsplit_df already has 'rep' and 'mouse_n' columns. 
#  If not, you need to extract them first using the same code as before.)
def is_bad_row(row):
    return (row['rep_N'], row['mouse_N']) in keys_to_remove

# 3. Filter nonsplit_df keeping only rows that are NOT in the set
# The '~' negates the boolean mask (Keep if NOT is_bad_row)
nonsplit_df = nonsplit_df[~nonsplit_df.apply(is_bad_row, axis=1)].copy()

{(2, 14), (2, 4), (2, 15), (1, 11), (2, 10), (1, 8), (2, 16), (2, 13), (2, 3), (2, 9), (1, 7), (2, 6), (2, 12), (1, 10), (1, 6), (2, 5), (2, 11), (1, 9)}

In [32]:
nonsplit_df

,zarr_address,region_id,mean_intensity_ch1,mean_intensity_ch2,area,bbox_rmin,bbox_rmax,bbox_cmin,bbox_cmax,mouse_N,rep_N,condition
16762,20250901_40X_TimerMtb_BP_mice2_mice3_mice4_DAP...,1,669.458333,1154.916667,72.0,12,28,24285,24311,2,1.0,DMSO
16763,20250901_40X_TimerMtb_BP_mice2_mice3_mice4_DAP...,2,394.212121,602.606061,33.0,31,46,25260,25278,2,1.0,DMSO
16764,20250901_40X_TimerMtb_BP_mice2_mice3_mice4_DAP...,3,613.163636,943.381818,55.0,43,59,25134,25166,2,1.0,DMSO
16765,20250901_40X_TimerMtb_BP_mice2_mice3_mice4_DAP...,4,737.836957,1462.576087,92.0,46,69,24763,24787,2,1.0,DMSO
16766,20250901_40X_TimerMtb_BP_mice2_mice3_mice4_DAP...,5,257.228070,396.228070,57.0,47,64,27340,27364,2,1.0,DMSO
...,...,...,...,...,...,...,...,...,...,...,...,...
49474,20251109_40X_Mouse16_Timer_PZA-RIF_20251109_09...,886,0.000000,0.000000,93.0,22391,22421,7838,7859,NaN,NaN,NaN
49475,20251109_40X_Mouse16_Timer_PZA-RIF_20251109_09...,887,0.000000,0.000000,43.0,23186,23203,4855,4877,NaN,NaN,NaN
49476,20251109_40X_Mouse16_Timer_PZA-RIF_20251109_09...,888,156.782051,119.256410,78.0,23481,23507,18800,18817,NaN,NaN,NaN
49477,20251109_40X_Mouse16_Timer_PZA-RIF_20251109_09...,889,1966.617391,445.739130,115.0,24371,24402,11851,11878,NaN,NaN,NaN
49478,20251109_40X_Mouse16_Timer_PZA-RIF_20251109_09...,890,588.700000,197.000000,40.0,24783,24802,16000,16020,NaN,NaN,NaN

## Add mouse and rep number

In [41]:
zarr_fn_pattern = "/mnt/OPERA3/Nathan/data/macrohet/mtb_tissue_localisation/data/whole_slice/rep*/mouse_*/zarr/*.zarr"

In [44]:
nonsplit_zarr_fns = [fn for fn in glob.glob(zarr_fn_pattern) if ('top' not in fn) 
                                                              & ('bot' not in fn) 
                                                              & ('left' not in fn) 
                                                              & ('right' not in fn)
                                                              & ('corrupted' not in fn)
                                                              & ('jnotebook' not in fn)]

In [46]:
fn = nonsplit_zarr_fns[0]

In [59]:
# --- 1. Build the Lookup Dictionary ---
meta_lookup = {}

for fn in nonsplit_zarr_fns:
    # Matches: /rep2/mouse_8/ or /rep2/mouse8/
    match = re.search(r'/rep(\d+)/mouse_?(\d+)/', fn)
    if match:
        rep = int(match.group(1))
        mouse = int(match.group(2))
        basename = os.path.basename(fn)
        meta_lookup[basename] = (rep, mouse)

# --- 2. Apply to DataFrame ---
# map() looks up every zarr_address in the dictionary efficiently
mapped_values = nonsplit_df['zarr_address'].map(meta_lookup)

# Extract the values into new columns
nonsplit_df['rep_N'] = mapped_values.str[0]    # The first item in the tuple (rep)
nonsplit_df['mouse_N'] = mapped_values.str[1]  # The second item in the tuple (mouse)
nonsplit_df['split'] = None                    # Set split to None

                                            zarr_address  rep_N  mouse_N split
16762  20250901_40X_TimerMtb_BP_mice2_mice3_mice4_DAP...      1        2  None
16763  20250901_40X_TimerMtb_BP_mice2_mice3_mice4_DAP...      1        2  None
16764  20250901_40X_TimerMtb_BP_mice2_mice3_mice4_DAP...      1        2  None
16765  20250901_40X_TimerMtb_BP_mice2_mice3_mice4_DAP...      1        2  None
16766  20250901_40X_TimerMtb_BP_mice2_mice3_mice4_DAP...      1        2  None

In [60]:
nonsplit_df

,zarr_address,region_id,mean_intensity_ch1,mean_intensity_ch2,area,bbox_rmin,bbox_rmax,bbox_cmin,bbox_cmax,mouse_N,rep_N,condition,split
16762,20250901_40X_TimerMtb_BP_mice2_mice3_mice4_DAP...,1,669.458333,1154.916667,72.0,12,28,24285,24311,2,1,DMSO,None
16763,20250901_40X_TimerMtb_BP_mice2_mice3_mice4_DAP...,2,394.212121,602.606061,33.0,31,46,25260,25278,2,1,DMSO,None
16764,20250901_40X_TimerMtb_BP_mice2_mice3_mice4_DAP...,3,613.163636,943.381818,55.0,43,59,25134,25166,2,1,DMSO,None
16765,20250901_40X_TimerMtb_BP_mice2_mice3_mice4_DAP...,4,737.836957,1462.576087,92.0,46,69,24763,24787,2,1,DMSO,None
16766,20250901_40X_TimerMtb_BP_mice2_mice3_mice4_DAP...,5,257.228070,396.228070,57.0,47,64,27340,27364,2,1,DMSO,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...
49474,20251109_40X_Mouse16_Timer_PZA-RIF_20251109_09...,886,0.000000,0.000000,93.0,22391,22421,7838,7859,16,2,NaN,None
49475,20251109_40X_Mouse16_Timer_PZA-RIF_20251109_09...,887,0.000000,0.000000,43.0,23186,23203,4855,4877,16,2,NaN,None
49476,20251109_40X_Mouse16_Timer_PZA-RIF_20251109_09...,888,156.782051,119.256410,78.0,23481,23507,18800,18817,16,2,NaN,None
49477,20251109_40X_Mouse16_Timer_PZA-RIF_20251109_09...,889,1966.617391,445.739130,115.0,24371,24402,11851,11878,16,2,NaN,None
49478,20251109_40X_Mouse16_Timer_PZA-RIF_20251109_09...,890,588.700000,197.000000,40.0,24783,24802,16000,16020,16,2,NaN,None

In [61]:
split_df

,zarr_address,region_id,mean_intensity_ch1,mean_intensity_ch2,area,bbox_rmin,bbox_rmax,bbox_cmin,bbox_cmax,rep_N,mouse_N,split
0,rep1_mouse6_bot.zarr,1,805.800000,1955.400000,35.0,125,143,14610,14626,1,6,bot
1,rep1_mouse6_bot.zarr,2,1001.546667,2004.760000,75.0,819,837,19047,19073,1,6,bot
2,rep1_mouse6_bot.zarr,3,387.137931,597.502463,203.0,913,943,13430,13460,1,6,bot
3,rep1_mouse6_bot.zarr,4,678.364865,844.472973,74.0,1350,1372,26076,26095,1,6,bot
4,rep1_mouse6_bot.zarr,5,458.293839,701.293839,633.0,1458,1499,8385,8424,1,6,bot
...,...,...,...,...,...,...,...,...,...,...,...,...
372342,rep2_mouse16_top.zarr,501,3168.583333,805.000000,156.0,34194,34228,2815,2845,2,16,top
372343,rep2_mouse16_top.zarr,502,3707.631579,913.567251,171.0,34204,34231,2751,2785,2,16,top
372344,rep2_mouse16_top.zarr,503,4872.142857,1180.142857,7.0,34211,34224,18594,18607,2,16,top
372345,rep2_mouse16_top.zarr,504,3681.236842,837.684211,38.0,34244,34263,765,781,2,16,top
372346,rep2_mouse16_top.zarr,505,5834.728395,1165.814815,81.0,34299,34317,17023,17049,2,16,top

## Merge whole df

In [101]:
df = pd.concat([nonsplit_df, split_df]).reset_index(drop=True)
df

,zarr_address,region_id,mean_intensity_ch1,mean_intensity_ch2,area,bbox_rmin,bbox_rmax,bbox_cmin,bbox_cmax,mouse_N,rep_N,condition,split
0,20250901_40X_TimerMtb_BP_mice2_mice3_mice4_DAP...,1,669.458333,1154.916667,72.0,12,28,24285,24311,2,1,DMSO,None
1,20250901_40X_TimerMtb_BP_mice2_mice3_mice4_DAP...,2,394.212121,602.606061,33.0,31,46,25260,25278,2,1,DMSO,None
2,20250901_40X_TimerMtb_BP_mice2_mice3_mice4_DAP...,3,613.163636,943.381818,55.0,43,59,25134,25166,2,1,DMSO,None
3,20250901_40X_TimerMtb_BP_mice2_mice3_mice4_DAP...,4,737.836957,1462.576087,92.0,46,69,24763,24787,2,1,DMSO,None
4,20250901_40X_TimerMtb_BP_mice2_mice3_mice4_DAP...,5,257.228070,396.228070,57.0,47,64,27340,27364,2,1,DMSO,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...
452360,rep2_mouse16_top.zarr,501,3168.583333,805.000000,156.0,34194,34228,2815,2845,16,2,NaN,top
452361,rep2_mouse16_top.zarr,502,3707.631579,913.567251,171.0,34204,34231,2751,2785,16,2,NaN,top
452362,rep2_mouse16_top.zarr,503,4872.142857,1180.142857,7.0,34211,34224,18594,18607,16,2,NaN,top
452363,rep2_mouse16_top.zarr,504,3681.236842,837.684211,38.0,34244,34263,765,781,16,2,NaN,top
452364,rep2_mouse16_top.zarr,505,5834.728395,1165.814815,81.0,34299,34317,17023,17049,16,2,NaN,top

### Add condition metadata

In [103]:
metadata =pd.read_pickle('/mnt/OPERA3/Nathan/data/macrohet/mtb_tissue_localisation/results/metadata.pkl')
metadata

,mouse_num,replicate,condition,basename_stem
0,1,1,H2O,20250815_40X_TimerMtb_BP_mice1_DAPI_TimerG_Tim...
1,2,1,DMSO,20250901_40X_TimerMtb_BP_mice2_mice3_mice4_DAP...
2,3,1,RIF,20250901_40X_TimerMtb_BP_mice2_mice3_mice4_DAP...
3,4,1,RIF,20250901_40X_TimerMtb_BP_mice2_mice3_mice4_DAP...
4,5,1,RIF,20250901_40X_TimerMtb_BP_mice5_mice6_mice7_DAP...
5,6,1,RIF,20250901_40X_TimerMtb_BP_mice5_mice6_mice7_DAP...
6,7,1,PZA,20250901_40X_TimerMtb_BP_mice5_mice6_mice7_DAP...
7,8,1,PZA,20250821_40X_TimerMtb_BP_mice8_mice9_DAPI_Time...
8,9,1,PZA,20250821_40X_TimerMtb_BP_mice8_mice9_DAPI_Time...
9,10,1,PZA,20250814_40X_TimerMtb_BP_mice10_DAPI_TimerG_Ti...
10,11,1,DMSO,20250901_40X_TimerMtb_BP_mice11_DAPI_TimerG_Ti...
0,1,2,H2O,20251001_40X_TimerMtb_BP_rep2_mice3_mice2_mice...
1,2,2,H2O,20251001_40X_TimerMtb_BP_rep2_mice3_mice2_mice...
2,3,2,H2O,20251001_40X_TimerMtb_BP_rep2_mice3_mice2_mice...
3,4,2,DMSO,20251014_40X_TimerMtb_BP_rep2_mice4_DAPI_Timer...
4,5,2,DMSO,20251014_40X_TimerMtb_BP_rep2_mice5_DAPI_Timer...
5,6,2,DMSO,20251014_40X_TimerMtb_BP_rep2_mice6_DAPI_Timer...
6,7,2,RIF,20251007_40X_TimerMtb_BP_rep2_mice7_mice8_mice...
7,8,2,RIF,20251007_40X_TimerMtb_BP_rep2_mice7_mice8_mice...
8,9,2,RIF,20251007_40X_TimerMtb_BP_rep2_mice7_mice8_mice...
9,10,2,RIF,20251030_40X_TimerMtb_BP_rep2_mice11_mice10_DA...

In [104]:
# 1. Define the specific new rows you want to add
new_data = [
    # Rep 2, Mouse 11 is RIF
    {'replicate': 2, 'mouse_num': 11, 'condition': 'RIF'}
]

# 2. Add Rep 2, Mouse > 11 as PZA
# Change (12, 16) to whatever your actual max mouse number is (e.g., up to 20?)
# range(12, 16) produces: 12, 13, 14, 15
for i in range(12, 17): 
    new_data.append({'replicate': 2, 'mouse_num': i, 'condition': 'PZA'})

# 3. Create a DataFrame from the new rows
new_df = pd.DataFrame(new_data)

# 4. Append to your existing metadata
# ignore_index=True resets the index so it's continuous
metadata = pd.concat([metadata, new_df], ignore_index=True)

In [105]:
metadata

,mouse_num,replicate,condition,basename_stem
0,1,1,H2O,20250815_40X_TimerMtb_BP_mice1_DAPI_TimerG_Tim...
1,2,1,DMSO,20250901_40X_TimerMtb_BP_mice2_mice3_mice4_DAP...
2,3,1,RIF,20250901_40X_TimerMtb_BP_mice2_mice3_mice4_DAP...
3,4,1,RIF,20250901_40X_TimerMtb_BP_mice2_mice3_mice4_DAP...
4,5,1,RIF,20250901_40X_TimerMtb_BP_mice5_mice6_mice7_DAP...
5,6,1,RIF,20250901_40X_TimerMtb_BP_mice5_mice6_mice7_DAP...
6,7,1,PZA,20250901_40X_TimerMtb_BP_mice5_mice6_mice7_DAP...
7,8,1,PZA,20250821_40X_TimerMtb_BP_mice8_mice9_DAPI_Time...
8,9,1,PZA,20250821_40X_TimerMtb_BP_mice8_mice9_DAPI_Time...
9,10,1,PZA,20250814_40X_TimerMtb_BP_mice10_DAPI_TimerG_Ti...
10,11,1,DMSO,20250901_40X_TimerMtb_BP_mice11_DAPI_TimerG_Ti...
11,1,2,H2O,20251001_40X_TimerMtb_BP_rep2_mice3_mice2_mice...
12,2,2,H2O,20251001_40X_TimerMtb_BP_rep2_mice3_mice2_mice...
13,3,2,H2O,20251001_40X_TimerMtb_BP_rep2_mice3_mice2_mice...
14,4,2,DMSO,20251014_40X_TimerMtb_BP_rep2_mice4_DAPI_Timer...
15,5,2,DMSO,20251014_40X_TimerMtb_BP_rep2_mice5_DAPI_Timer...
16,6,2,DMSO,20251014_40X_TimerMtb_BP_rep2_mice6_DAPI_Timer...
17,7,2,RIF,20251007_40X_TimerMtb_BP_rep2_mice7_mice8_mice...
18,8,2,RIF,20251007_40X_TimerMtb_BP_rep2_mice7_mice8_mice...
19,9,2,RIF,20251007_40X_TimerMtb_BP_rep2_mice7_mice8_mice...
20,10,2,RIF,20251030_40X_TimerMtb_BP_rep2_mice11_mice10_DA...
21,11,2,RIF,NaN
22,12,2,PZA,NaN
23,13,2,PZA,NaN
24,14,2,PZA,NaN
25,15,2,PZA,NaN
26,16,2,PZA,NaN

In [106]:
# 1. Drop 'condition' from your main df if it already exists.
#    This prevents the creation of 'condition_x' and 'condition_y'.
df = df.drop(columns=['condition'])

# 2. Perform the Left Merge
#    We assume 'metadata' is the master list, so we pull 'condition' from there.
df = df.merge(
    metadata[['replicate', 'mouse_num', 'condition']], 
    left_on=['rep_N', 'mouse_N'],        # Keys in main df
    right_on=['replicate', 'mouse_num'], # Keys in metadata
    how='left'
)

# 3. Clean up the extra keys
#    The merge added 'replicate' and 'mouse_num'; we drop them to keep df clean.
df = df.drop(columns=['replicate', 'mouse_num'])

In [110]:
df

,zarr_address,region_id,mean_intensity_ch1,mean_intensity_ch2,area,bbox_rmin,bbox_rmax,bbox_cmin,bbox_cmax,mouse_N,rep_N,split,condition
0,20250901_40X_TimerMtb_BP_mice2_mice3_mice4_DAP...,1,669.458333,1154.916667,72.0,12,28,24285,24311,2,1,None,DMSO
1,20250901_40X_TimerMtb_BP_mice2_mice3_mice4_DAP...,2,394.212121,602.606061,33.0,31,46,25260,25278,2,1,None,DMSO
2,20250901_40X_TimerMtb_BP_mice2_mice3_mice4_DAP...,3,613.163636,943.381818,55.0,43,59,25134,25166,2,1,None,DMSO
3,20250901_40X_TimerMtb_BP_mice2_mice3_mice4_DAP...,4,737.836957,1462.576087,92.0,46,69,24763,24787,2,1,None,DMSO
4,20250901_40X_TimerMtb_BP_mice2_mice3_mice4_DAP...,5,257.228070,396.228070,57.0,47,64,27340,27364,2,1,None,DMSO
...,...,...,...,...,...,...,...,...,...,...,...,...,...
452360,rep2_mouse16_top.zarr,501,3168.583333,805.000000,156.0,34194,34228,2815,2845,16,2,top,PZA
452361,rep2_mouse16_top.zarr,502,3707.631579,913.567251,171.0,34204,34231,2751,2785,16,2,top,PZA
452362,rep2_mouse16_top.zarr,503,4872.142857,1180.142857,7.0,34211,34224,18594,18607,16,2,top,PZA
452363,rep2_mouse16_top.zarr,504,3681.236842,837.684211,38.0,34244,34263,765,781,16,2,top,PZA
452364,rep2_mouse16_top.zarr,505,5834.728395,1165.814815,81.0,34299,34317,17023,17049,16,2,top,PZA

In [111]:
df.to_pickle('/mnt/OPERA3/Nathan/data/macrohet/mtb_tissue_localisation/results/sc_mtb_tissue.pkl')